### ISSUE TITLE
time prefix not display

### ISSUE THREAD

**Issue by navono** [akoidan/lines-logger#5]
make demo as README instructions:
```
import {Logger, LoggerFactory} from 'lines-logger';

let factory: LoggerFactory = new LoggerFactory();
let logger: Logger = factory.getLogger('tag');

logger.log('Hello world')(); // pay attention to () in the end. `logger.log` returns a function that should be called, thus `console.log` is called from YOUR location instead of the library.
logger.debug('My array is {}, object is {}', [1,2,3], {1:1, 2:2})();
```

in Console output, there no time dispaly before tag name.

**Comment by navono** [comment]
There no time in params in `getSingleLoggerStype`.

**Comment by akoidan** [comment]
Yes I also thought about this feature. But most browsers have this feature in the settings window, which make it far more convenient. Timestamps really eat space. But you can disable/enable it in the settings winwdow. E.g. chrome's one:

![image](https://user-images.githubusercontent.com/1336703/113994363-fc777600-985d-11eb-839d-50073bedea9f.png)

![image](https://user-images.githubusercontent.com/1336703/113994213-e073d480-985d-11eb-8aaf-f737bd390b7b.png)

![image](https://user-images.githubusercontent.com/1336703/113994140-cf2ac800-985d-11eb-95a1-082ae2c1b52f.png)

**Comment by navono** [comment]
Yeah, you're right. 
Just for note: [console-log-timestamps-in-chrome](https://stackoverflow.com/questions/12008120/console-log-timestamps-in-chrome) for `Chrome 68+`.
